version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flashcards
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    build: ./backend
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/flashcards?schema=public"
      NODE_ENV: development
    depends_on:
      - db
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/usr/src/app
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
    environment:
      NODE_ENV: development

volumes:
  pgdata:
